model:
  vision_model: "biovil"
  language_model: 
    name: "emrecanacikgoz/opt-125m-MedMCQA-radiology"
    inference:
      load_in_8bit: true
  tie_mappers: false
  image_dropout: 0.1
  shared_emb_dim: 512
  max_length: 112
  num_img_tokens: 1

trainer:
  accelerator: "gpu"
  devices: 1
  precision: "16-mixed"
  max_steps: 100

# data loader
loader:
  batch_size: 16
  pin_memory: true
  num_workers: 4

# logger (tensorboard)
logger:
  name: "debug_2"
  project: "fromage"
  version: "debug_2"
  save_dir: "logs/"

dataset:
  name: "MIMIC-CXR-JPG"
  resize: 512
  center_crop_size: 480
  tsv_path: "data/MIMIC_JPG_<SPLIT>.tsv"
  img_path: "/datasets/mimic/cxr-jpg/physionet.org/files/mimic-cxr-jpg/2.0.0/files/"

optimizer:
  algorithm: 'AdamW'
  gradient_clip_val: 1.0
  grad_acc_step: 1
  params:
    lr: 1.0e-2
    weight_decay: 0

# checkpoint
checkpoint:
  save_top_k: 1
  save_last: true
  verbose: true
  monitor: "caption_loss/val"
  mode: "min"

ckpt_path: 
  ckpt_path: null

# hydra-specific
hydra:
  run:
    dir: .

defaults:
  - _self_
  - override hydra/job_logging: disabled