model:
  vision_model: "biovil"
  language_model: "facebook/opt-125m"
  tie_mappers: true
  image_dropout: 0.1
  max_length: 112
  num_img_tokens: 1

trainer:
  accelerator: "gpu"
  devices: 1
  precision: "16-mixed"
  max_epochs: 10

# data loader
loader:
  batch_size: 72
  pin_memory: true
  num_workers: 4

# logger (tensorboard)
logger:
  name: "tied_test_2"
  project: "fromage"
  version: "tied_test_2"
  save_dir: "logs/"

dataset:
  name: "MIMIC-CXR-JPG"
  resize: 512
  center_crop_size: 480
  tsv_path: "data/MIMIC_JPG_<SPLIT>.tsv"
  img_path: "/kuacc/users/oince22/hpc_run/physionet.org/files/mimic-cxr-jpg/2.0.0/files/"

optimizer:
  algorithm: 'AdamW'
  gradient_clip_val: 1.0
  params:
    lr: 5.0e-5
    weight_decay: 5.0e-5

# checkpoint
checkpoint:
  save_top_k: 1
  save_last: true
  verbose: true
  monitor: "caption_loss/val"
  mode: "min"

ckpt_path: 
  ckpt_path: null

# hydra-specific
hydra:
  run:
    dir: .

defaults:
  - _self_
  - override hydra/job_logging: disabled
