model:
  vision_model: "biovil"
  language_model: "facebook/opt-350m"
  tie_mappers: false

trainer:
  accelerator: "gpu"
  devices: 1
  max_epochs: 2
  precision: 32

# data loader
loader:
  batch_size: 40
  pin_memory: true
  num_workers: 4

# logger (tensorboard)
logger:
  name: "test_2"
  project: "fromage"
  version: "test_2"
  save_dir: "logs/"

dataset:
  name: "MIMIC-CXR-JPG"
  path: "/kuacc/users/oince22/hpc_run/physionet.org/files/mimic-cxr-jpg/"

optimizer:
  algorithm: 'AdamW'
  gradient_clip_val: 1.0
  params:
    lr: 0.00005
    weight_decay: 0.0001

# checkpoint
checkpoint:
  save_top_k: 1
  save_last: true
  verbose: true
  monitor: "caption_loss"
  mode: "min"

ckpt_path: 
  ckpt_path: null

# hydra-specific
hydra:
  run:
    dir: .

defaults:
  - _self_
  - override hydra/job_logging: disabled
